### ISSUE TITLE
Chapter 22: Integrating SpriteKit: Car game does not build on MacOS 11.3 / Xcode 12.5

### ISSUE THREAD

**Issue by IngoKoch** [raywenderlich/met-materials#1]
I could workaround it by removing core image::srgb_to_linear in CIBlend.metal.
But then the application starts and stalls rendering the screen black.
Would be great if this could be fixed.

**Comment by jellodiil** [comment]
Hey there,
The new edition of this books is out on Wednesday, 6th April 2022 — it should be fixed in this edition. 
If not, please post on the forum of this book: [https://forums.raywenderlich.com/c/books/metal-by-tutorials](https://forums.raywenderlich.com/c/books/metal-by-tutorials)
